# Generated by Django 6.1 on 2026-08-15 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking_ticket_number_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('WEEKEND', 'Weekend Deals'), ('DOMESTIC', 'Domestic Offers'), ('INTERNATIONAL', 'International Offers'), ('BUSINESS', 'Business Class Deals'), ('STUDENT', 'Student Offers'), ('FAMILY', 'Family Offers'), ('LASTMINUTE', 'Last-Minute Deals')], default='DOMESTIC', max_length=30)),
                ('badge', models.CharField(default='🔥 Special Deal', max_length=50)),
                ('description', models.TextField()),
                ('discount_percent', models.FloatField(default=10.0)),
                ('origin_code', models.CharField(blank=True, help_text='Specific origin or empty for any', max_length=10, null=True)),
                ('destination_code', models.CharField(blank=True, help_text='Specific destination or empty for any', max_length=10, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=2999.0, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_passengers', models.IntegerField(default=1)),
                ('max_passengers', models.IntegerField(default=9)),
                ('required_class', models.CharField(blank=True, help_text='e.g. BUSINESS, FIRST, ECONOMY or null', max_length=20, null=True)),
                ('is_international_only', models.BooleanField(default=False)),
                ('terms', models.TextField(blank=True, default='Valid for limited time. Applicable on select routes. Subject to seat availability.')),
                ('countdown_hours', models.IntegerField(default=48, help_text='Simulated countdown hours')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='deal_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='flights.deal'),
        ),
    ]
