# Generated by Django 6.1 on 2026-08-16 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_booking_cancellation_fee_booking_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='baggage_policy',
            field=models.TextField(blank=True, default='Cabin: 7kg | Check-in: 15kg (Domestic), 25kg (Intl)'),
        ),
        migrations.AddField(
            model_name='airline',
            name='cabin_classes',
            field=models.CharField(default='Economy, Premium Economy, Business, First', max_length=150),
        ),
        migrations.AddField(
            model_name='airline',
            name='contact_email',
            field=models.EmailField(blank=True, default='support@airline.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='contact_phone',
            field=models.CharField(blank=True, default='+91 1800-102-3456', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='fleet_size',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='airline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='avg_fare',
            field=models.DecimalField(decimal_places=2, default=4500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='airport',
            name='best_season',
            field=models.CharField(default='Oct - Mar', max_length=100),
        ),
        migrations.AddField(
            model_name='airport',
            name='category',
            field=models.CharField(choices=[('CITY', 'Metropolitan / City'), ('BEACH', 'Beach & Coastal'), ('MOUNTAINS', 'Hills & Mountains'), ('HERITAGE', 'Heritage & Culture'), ('ADVENTURE', 'Adventure & Nature'), ('INTERNATIONAL', 'Global Gateway')], default='CITY', max_length=30),
        ),
        migrations.AddField(
            model_name='airport',
            name='country_code',
            field=models.CharField(default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(default=20.5937),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(default=78.9629),
        ),
        migrations.AddField(
            model_name='airport',
            name='popularity',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='airport',
            name='region',
            field=models.CharField(default='Asia', max_length=100),
        ),
        migrations.AddField(
            model_name='airport',
            name='terminal',
            field=models.CharField(default='T1/T2', max_length=50),
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='UTC+05:30', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='applicable_airlines',
            field=models.CharField(blank=True, help_text='Comma-separated airline codes or blank for all', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='applicable_destinations',
            field=models.TextField(blank=True, help_text='Comma-separated destination codes', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='applicable_flights',
            field=models.CharField(blank=True, help_text='Comma-separated flight numbers or blank for all', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='applied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='bookings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='min_booking_amount',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='per_user_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='deal',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_discount_given',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='trip_type',
            field=models.CharField(choices=[('BOTH', 'One Way & Round Trip'), ('ONE_WAY', 'One Way Only'), ('ROUND_TRIP', 'Round Trip Only')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='usage_limit',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='deal',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farehistory',
            name='reason',
            field=models.CharField(default='Dynamic Calculation', max_length=200),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='manual_override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_fare_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='min_fare_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('IN_FLIGHT', 'In Flight'), ('LANDED', 'Landed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('WEEKEND', 'Weekend Deals'), ('DOMESTIC', 'Domestic Offers'), ('INTERNATIONAL', 'International Offers'), ('BUSINESS', 'Business Class Deals'), ('STUDENT', 'Student Offers'), ('FAMILY', 'Family Offers'), ('LASTMINUTE', 'Last-Minute Deals'), ('BEACH', 'Beach Escapes'), ('CITY', 'City Breaks'), ('HERITAGE', 'Heritage Tours'), ('ADVENTURE', 'Adventure')], default='DOMESTIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SELECTED', 'Selected'), ('OCCUPIED', 'Occupied'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FLIGHT_CREATE', 'Flight Created'), ('FLIGHT_UPDATE', 'Flight Updated'), ('FLIGHT_DISABLE', 'Flight Disabled'), ('PRICE_OVERRIDE', 'Price Override Applied'), ('BULK_PRICE_CHANGE', 'Bulk Price Adjustment'), ('PRICING_RULE_CHANGE', 'Pricing Rule Modified'), ('DEAL_CREATE', 'Deal Created'), ('DEAL_UPDATE', 'Deal Updated'), ('DEAL_DUPLICATE', 'Deal Duplicated'), ('DEAL_DISABLE', 'Deal Disabled'), ('SEAT_BLOCK', 'Seat Blocked/Unblocked'), ('BOOKING_CANCEL', 'Booking Cancelled by Admin'), ('REFUND_APPROVE', 'Refund Approved'), ('REFUND_REJECT', 'Refund Rejected'), ('AIRPORT_MODIFY', 'Airport Modified'), ('AIRLINE_MODIFY', 'Airline Modified'), ('USER_STATUS_CHANGE', 'User Status Changed')], max_length=40)),
                ('entity_type', models.CharField(default='General', max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('INFO', 'Informational 🟢'), ('WARNING', 'Warning 🟡'), ('HIGH', 'High Priority 🟠'), ('CRITICAL', 'Critical Alert 🔴')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('action_recommended', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.booking')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.deal')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Dynamic Rule', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_fare_floor', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('max_fare_cap', models.DecimalField(decimal_places=2, default=45000.0, max_digits=10)),
                ('demand_multiplier_weight', models.FloatField(default=1.1, help_text='Weight for demand curve')),
                ('seat_availability_weight', models.FloatField(default=1.2, help_text='Weight for seat scarcity')),
                ('time_to_departure_weight', models.FloatField(default=1.15, help_text='Weight for approaching departure')),
                ('peak_season_multiplier', models.FloatField(default=1.2, help_text='Peak holiday multiplier')),
                ('weekend_multiplier', models.FloatField(default=1.15, help_text='Fri-Sun travel multiplier')),
                ('holiday_multiplier', models.FloatField(default=1.25, help_text='Special festive travel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
