# Generated by Django 6.1 on 2026-08-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_airline_baggage_policy_airline_cabin_classes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='OPERATIONAL', max_length=30)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('last_successful_request', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('uptime_pct', models.FloatField(default=99.9)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(default='India', max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_required', models.CharField(default='Required', max_length=50)),
                ('visa_type', models.CharField(default='Tourist / Electronic Visa', max_length=100)),
                ('passport_validity', models.CharField(default='Minimum 6 months from travel date', max_length=100)),
                ('documents_required', models.TextField(default='Valid Passport, Confirmed Return Ticket, Hotel Booking / Accommodation Proof, Proof of Funds')),
                ('entry_requirements', models.TextField(default='Customs declaration upon entry, health declaration if applicable.')),
                ('transit_requirements', models.TextField(default='Transit visa required if leaving airport international transit area.')),
                ('important_notes', models.TextField(default='Travel requirements may change without prior notice. Verify with official government/embassy sources.')),
                ('official_source_url', models.URLField(blank=True, default='https://www.iatatravelcentre.com/', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='gate',
            field=models.CharField(default='A12', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='terminal',
            field=models.CharField(default='T1', max_length=20),
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('travel_date', models.DateField()),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_alerts', to='flights.airport')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='flights.flight')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_alerts', to='flights.airport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
