# Generated by Django 6.1 on 2026-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_servicehealthlog_travelrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
